### PR TITLE
Task Issue 21

### LINKED ISSUE #21: An issue with the productLinks unique index
### Issue
Currently, we relying on the the `{ "productLinks.name": 1, "productLinks.foreignKey": 1 }` multi-key, unique index to prevent duplicate items. While this is great in theory, it may not work for our current workflow. 

I did some reading on `unique` indexes in Mongo for missing fields ([docs](https://docs.mongodb.com/manual/indexes/#unique-indexes)) and due to this constraint, we would not be able to have multiple account documents in the database with an empty `productLinks` array. Our current workflow as I understand it is:

1. Product calls [`createUser`](https://github.com/bufferapp/authentication-service/blob/b8869b403ce6dcde7ecc3294eca387fc4f784111/src/createUser.js) to create a user account w/ an email and password without a product link
2. Product (ex. Reply) creates it's own local product user
3. Product calls `createProductLink` to add a link to the user account created in step 1

With this index, if a second user was created in between step 1 and 3 it would fail as they both would have an empty `productLinks` array. I pulled a Mongo 3.6 docker image locally to test this and have been able to confirm this behavior.

### Potential solutions

1. Not use a unique index for this field and instead enforce uniqueness using a `findOne` then `update` approach.
2. Use a sparse, unique index ([docs](https://docs.mongodb.com/manual/core/index-sparse/#sparse-and-unique-properties))
3. Use a partial index w/ a Unique constraint ([docs](https://docs.mongodb.com/manual/core/index-partial/#partial-index-with-unique-constraints))
4. Modify our approach to force a productLink to be created upon user creation

We could potentially do idea 4, but long term, I think we wouldn't want to force this when we have true multi-product signup process so I may want to focus on the other two or perhaps another idea that I haven't listed.

I'm personally fine with both idea 1, 2, or 3. I haven't ever used partial or for that matter unique indexes so this is new territory for me 😄. Idea 2 is maybe the simplest that still relies on mongo for the uniqueness validation. I gave idea 2 a spin on a local mongo 3.6 database and it seems to work nicely.

If we did idea 3, we could use an index like this as we wouldn't be sure if `productLink` exists or is an empty array:
```js
{ "productLinks.name": 1, "productLinks.foreignKey": 1 }, 
{
  unique: 1, 
  partialFilterExpression: { $and: [{ productLinks: { $exists: 1 } }, { productLinks: { $not: { $size: 0 } } }] } 
}
```

In reviewing how complex that is, it seems that 1 and 2 might be the front-runners for a solution, but I think we should test them out on a database again depending on what we choose.

What do you think @hharnisc?

### PR DESCRIPTION
**Pull request by hharnisc**
fixes #21 

also fixes a few bugs found during manual testing

### CODE REVIEW

File: src/authenticationAccountModel.js [hunk 1]
```diff
@@ -70,11 +73,14 @@ module.exports = ({ mongooseConnection }) => {
...
       'productlinks.foreignKey': 1,
     },
-    { unique: true },
+    { unique: true, sparse: true },
   )
 
   // bump the updatedAt feild on save
   authenticationAccountSchema.pre('save', async function() {
+    if (this.hashedPassword === DEFAULT_PASSWORD_PLACEHOLDER) {
+      throw new Error('Password has not been hashed')
```
Comment (djfarrelly) [inline src/authenticationAccountModel.js]: 👍
